
import { Language, DocType } from './types';

export const VAT_RATE_BH = 17;

export const VAT_CATEGORIES = [
  { label: 'Standardna (17%)', value: 17, code: 'S' },
  { label: 'Izvoz (0%)', value: 0, code: 'E' },
  { label: 'Oslobođeno (Čl. 24/25)', value: 0, code: 'O' }
];

export const TRANSLATIONS: Record<Language, any> = {
  BS: {
    dashboard: 'Kontrolna tabla',
    invoices: 'Računi',
    offers: 'Ponude',
    calculations: 'Kalkulacije',
    orders: 'Narudžbenice',
    clients: 'Klijenti',
    inventory: 'Lager Lista',
    settings: 'Postavke',
    accounting: 'Računovodstvo',
    reports: 'Izvještaji',
    newDoc: 'Novi dokument',
    save: 'Sačuvaj',
    print: 'Štampaj',
    clientName: 'Naziv klijenta',
    address: 'Adresa',
    total: 'Ukupno',
    subtotal: 'Osnovica',
    vat: 'PDV',
    grandTotal: 'Ukupno za uplatu',
    itemDescription: 'Opis stavke',
    qty: 'Kol.',
    unit: 'Jed.',
    price: 'Cijena',
    jib: 'JIB',
    pdv: 'PDV broj',
    date: 'Datum izdavanja',
    dueDate: 'Datum dospijeća',
    deliveryDate: 'Datum isporuke',
    place: 'Mjesto izdavanja',
    paymentMethod: 'Način plaćanja',
    fiscalNumber: 'Fiskalni isječak br.',
    back: 'Nazad',
    companyInfo: 'Podaci o firmi',
    bank: 'Banka',
    account: 'Žiro račun',
    note: 'Napomena / VAT Exempt Note',
    language: 'Jezik',
    inventoryItems: 'Artikli na stanju',
    code: 'Šifra',
    stock: 'Zaliha',
    clone: 'Kopiraj',
    convertToInvoice: 'Pretvori u račun',
    dualLanguage: 'Dvojezični prikaz (BS/EN)',
    docTypeNames: {
      [DocType.INVOICE]: 'Račun-Otpremnica',
      [DocType.OFFER]: 'Ponuda',
      [DocType.CALCULATION]: 'Kalkulacija',
      [DocType.PURCHASE_ORDER]: 'Narudžbenica'
    }
  },
  EN: {
    dashboard: 'Dashboard',
    invoices: 'Invoices',
    offers: 'Offers',
    calculations: 'Calculations',
    orders: 'Purchase Orders',
    clients: 'Clients',
    inventory: 'Inventory',
    settings: 'Settings',
    accounting: 'Accounting',
    reports: 'Reports',
    newDoc: 'New Document',
    save: 'Save',
    print: 'Print',
    clientName: 'Client Name',
    address: 'Address',
    total: 'Total',
    subtotal: 'Subtotal',
    vat: 'VAT',
    grandTotal: 'Grand Total',
    itemDescription: 'Item Description',
    qty: 'Qty',
    unit: 'Unit',
    price: 'Price',
    jib: 'ID Number',
    pdv: 'VAT Number',
    date: 'Issue Date',
    dueDate: 'Due Date',
    deliveryDate: 'Delivery Date',
    place: 'Place of Issue',
    paymentMethod: 'Payment Method',
    fiscalNumber: 'Fiscal Receipt No.',
    back: 'Back',
    companyInfo: 'Company Info',
    bank: 'Bank',
    account: 'Bank Account',
    note: 'Note',
    language: 'Language',
    inventoryItems: 'Stock Items',
    code: 'Code',
    stock: 'Stock',
    clone: 'Clone',
    convertToInvoice: 'Convert to Invoice',
    dualLanguage: 'Dual Language Mode (BS/EN)',
    docTypeNames: {
      [DocType.INVOICE]: 'Invoice',
      [DocType.OFFER]: 'Offer',
      [DocType.CALCULATION]: 'Calculation',
      [DocType.PURCHASE_ORDER]: 'Purchase Order'
    }
  }
};
